version: '3'
services:
    mysql-service:
        image: mysql:8.0.27
        volumes:
            - ./deploy/db_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD
        ports:
            - 3306:3306

    clockzy-api:
        build:
            context: .
            dockerfile: ./deploy/Dockerfile
        ports:
            - 10030:10030
        volumes:
            - ./:/app
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        working_dir: /app
        environment:
            - PYTHONUNBUFFERED=1
            - GUNICORN=1
        command: >
                bash -c "python3 setup.py install && cd /app/src/clockzy/services &&
                         python3 -m gunicorn --bind 0.0.0.0:10030 -w 2 --access-logfile /app/logs/clockzy_service.log \
                         --timeout 300 clockzy_service:clockzy_service"
        depends_on:
            - mysql-service
        links:
            - mysql-service

    clockzy-web:
        build:
            context: .
            dockerfile: ./deploy/Dockerfile
        ports:
            - 10025:10025
        volumes:
            - ./:/app
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        working_dir: /app
        environment:
            - PYTHONUNBUFFERED=1
            - GUNICORN=1
        command: >
                bash -c "python3 setup.py install && cd /app/src/web_app &&
                         python3 -m gunicorn --bind 0.0.0.0:10025 -w 2 \
                         --access-logfile /app/logs/clockzy_web_service.log --timeout 300 clockzy_web:web_app"
        depends_on:
            - mysql-service
            - clockzy-api

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
