"""GLOBAL VARIABLES"""

# API PATHS
ECHO_REQUEST = '/echo'
SIGN_UP_REQUEST = '/sign-up'
UPDATE_USER_REQUEST = '/update-user'
DELETE_USER_REQUEST = '/delete-user'
CLOCK_REQUEST = '/clock'
TIME_REQUEST = '/time'
TIME_HISTORY_REQUEST = '/time-history'
CLOCK_HISTORY_REQUEST = '/clock-history'
TODAY_INFO_REQUEST = '/today'
COMMAND_HELP_REQUEST = '/help'
ADD_ALIAS_REQUEST = '/alias'
GET_ALIASES_REQUEST = '/get-aliases'
CHECK_USER_STATUS_REQUEST = '/check'
ENABLE_INTRATIME_INTEGRATION_REQUEST = '/enable-intratime'
DISABLE_INTRATIME_INTEGRATION_REQUEST = '/disable-intratime'
MANAGEMENT_REQUEST = '/management'
